### ISSUE TITLE
Error on Librelec Matrix

### ISSUE THREAD

**Issue by fabpolli** [Dis90/plugin.video.discoveryplus#91]
Just downloaded repo from URL, installed the addon and configured cookie file but on one device (Raspberry 4) I hava this error on log:
2023-04-09 10:44:53.810 T:1544    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'json.decoder.JSONDecodeError'>
                                                   Error Contents: Expecting value: line 1 column 1 (char 0)
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.discoveryplus/default.py", line 5, in <module>
                                                       addon.run()
                                                     File "/storage/.kodi/addons/plugin.video.discoveryplus/resources/lib/addon.py", line 15, in run
                                                       plugin.run()
                                                     File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 130, in run
                                                       self._dispatch(self.path)
                                                     File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 141, in _dispatch
                                                       view_func(**kwargs)
                                                     File "/storage/.kodi/addons/plugin.video.discoveryplus/resources/lib/addon.py", line 30, in list_menu
                                                       anonymous_user = helper.d.get_user_data()['attributes']['anonymous']
                                                     File "/storage/.kodi/addons/plugin.video.discoveryplus/resources/lib/dplay.py", line 261, in get_user_data
                                                       return json.loads(data)['data']
                                                     File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
                                                     File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
                                                     File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
                                                   json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
                                                   -->End of Python script error report<--
                                                   
2023-04-09 10:44:54.379 T:1544     INFO <general>: Python interpreter stopped
2023-04-09 10:44:54.387 T:1543    ERROR <general>: GetDirectory - Error getting plugin://plugin.video.discoveryplus/
2023-04-09 10:44:54.419 T:1034    ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.discoveryplus/) failed
2023-04-09 10:45:53.648 T:1080     INFO <general>: ES: Client  from ::ffff:192.168.1.110 timed out
2023-04-09 10:46:54.658 T:1087     INFO <general>: JSONRPC Server: Disconnection detected
2023-04-09 10:47:00.443 T:1087     INFO <general>: JSONRPC Server: New connection added

Seem to be missing requirement?

**Comment by fabpolli** [comment]
After some relaunch of plugin It started normally, maybe the problem was linked to discovery plus website unavailability
