### ISSUE TITLE
Error with 'All Sports' on Kodi 21.0

### ISSUE THREAD

**Issue by prothed99** [Dis90/plugin.video.discoveryplus#99]
Installed this addon on two Kodi 21.0 systems - both show videos without error except when navigating to 'All Sports' which fails.  The error message says to check the kodi log which contains the error shown below.

When the repository is installed it indicates that the addon may only be for kodi 19.  If so, is an update feasible?
Thank you.

2024-07-31 15:46:33.137 T:6168    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'KeyError'>
                                                   Error Contents: 'routes'
                                                   Traceback (most recent call last):
                                                     File "C:\Users\xxxx\AppData\Roaming\Kodi\addons\plugin.video.discoveryplus\default.py", line 5, in <module>
                                                       addon.run()
                                                     File "C:\Users\xxxx\AppData\Roaming\Kodi\addons\plugin.video.discoveryplus\resources\lib\addon.py", line 15, in run
                                                       plugin.run()
                                                     File "C:\Users\xxxx\AppData\Roaming\Kodi\addons\script.module.routing\lib\routing.py", line 130, in run
                                                       self._dispatch(self.path)
                                                     File "C:\Users\xxxx\AppData\Roaming\Kodi\addons\script.module.routing\lib\routing.py", line 141, in _dispatch
                                                       view_func(**kwargs)
                                                     File "C:\Users\xxxx\AppData\Roaming\Kodi\addons\plugin.video.discoveryplus\resources\lib\addon.py", line 137, in list_page
                                                       list_page_us(page_path=page_path)
                                                     File "C:\Users\xxxx\AppData\Roaming\Kodi\addons\plugin.video.discoveryplus\resources\lib\addon.py", line 172, in list_page_us
                                                       list_collection(collection_id=collection['id'], page=1)
                                                     File "C:\Users\xxxx\AppData\Roaming\Kodi\addons\plugin.video.discoveryplus\resources\lib\addon.py", line 1491, in list_collection
                                                       next_page_path = [x['attributes']['url'] for x in routes if
                                                     File "C:\Users\xxxx\AppData\Roaming\Kodi\addons\plugin.video.discoveryplus\resources\lib\addon.py", line 1492, in <listcomp>
                                                       x['id'] == taxonomyNode['relationships']['routes']['data'][0]['id']][0]
                                                   KeyError: 'routes'
                                                   -->End of Python script error report<--
                                                   
2024-07-31 15:46:33.300 T:12140   error <general>: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.discoveryplus/page/all-sports
2024-07-31 15:46:33.307 T:11156   error <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.discoveryplus/page/all-sports) failed

**Comment by Dis90** [comment]
What country are you in? That would make it easier to solve the problem. What route did you take to the "All Sports" category? Home -> Sports -> ??

The plugin should work with Kodi 21 but I haven't tried it.

**Comment by prothed99** [comment]
Hi,

I'm in the UK.
The route is   home , sports , all sports.

I've tested on an Amazon fire stick and on windows 10

You may see a sudden increase in use of the add-on since Eurosport has now
been terminated and incorporated into Discovery!

Best wishes,
Dave.

**Comment by Dis90** [comment]
Can you try with this https://github.com/Dis90/plugin.video.discoveryplus/tree/issue99 -> Code -> Download ZIP
if that fixes the problem.

**Comment by P1st0nBr0ke** [comment]
Same issue here (also in the UK).

After a clean install using the zip file linked to above, the issue appears to be fixed.

That said, is it normal behavior for the addon to throw an error when upcoming events are clicked prior to being aired?

**Comment by Dis90** [comment]
Thanks for the confirmation.

> That said, is it normal behavior for the addon to throw an error when upcoming events are clicked prior to being aired?

Yes that is normal behavior.

**Comment by P1st0nBr0ke** [comment]
Many thanks for clarifying, and for the addon.
